//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.GymAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfFloat", Namespace="http://tempuri.org/", ItemName="float")]
    [System.SerializableAttribute()]
    public class ArrayOfFloat : System.Collections.Generic.List<float> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GymAPI.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name dataGrid_DataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dataGrid_Data", ReplyAction="*")]
        UI.GymAPI.dataGrid_DataResponse dataGrid_Data(UI.GymAPI.dataGrid_DataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dataGrid_Data", ReplyAction="*")]
        System.Threading.Tasks.Task<UI.GymAPI.dataGrid_DataResponse> dataGrid_DataAsync(UI.GymAPI.dataGrid_DataRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        UI.GymAPI.SaveResponse Save(UI.GymAPI.SaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<UI.GymAPI.SaveResponse> SaveAsync(UI.GymAPI.SaveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataGrid_DataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dataGrid_Data", Namespace="http://tempuri.org/", Order=0)]
        public UI.GymAPI.dataGrid_DataRequestBody Body;
        
        public dataGrid_DataRequest() {
        }
        
        public dataGrid_DataRequest(UI.GymAPI.dataGrid_DataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dataGrid_DataRequestBody {
        
        public dataGrid_DataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataGrid_DataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dataGrid_DataResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI.GymAPI.dataGrid_DataResponseBody Body;
        
        public dataGrid_DataResponse() {
        }
        
        public dataGrid_DataResponse(UI.GymAPI.dataGrid_DataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dataGrid_DataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UI.GymAPI.ArrayOfString[] dataGrid_DataResult;
        
        public dataGrid_DataResponseBody() {
        }
        
        public dataGrid_DataResponseBody(UI.GymAPI.ArrayOfString[] dataGrid_DataResult) {
            this.dataGrid_DataResult = dataGrid_DataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://tempuri.org/", Order=0)]
        public UI.GymAPI.SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(UI.GymAPI.SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public UI.GymAPI.ArrayOfFloat medidas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char genero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fecha;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(string nombre, UI.GymAPI.ArrayOfFloat medidas, int edad, char genero, System.DateTime fecha) {
            this.nombre = nombre;
            this.medidas = medidas;
            this.edad = edad;
            this.genero = genero;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI.GymAPI.SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(UI.GymAPI.SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveResponseBody {
        
        public SaveResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : UI.GymAPI.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<UI.GymAPI.WebServiceSoap>, UI.GymAPI.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI.GymAPI.dataGrid_DataResponse UI.GymAPI.WebServiceSoap.dataGrid_Data(UI.GymAPI.dataGrid_DataRequest request) {
            return base.Channel.dataGrid_Data(request);
        }
        
        public UI.GymAPI.ArrayOfString[] dataGrid_Data() {
            UI.GymAPI.dataGrid_DataRequest inValue = new UI.GymAPI.dataGrid_DataRequest();
            inValue.Body = new UI.GymAPI.dataGrid_DataRequestBody();
            UI.GymAPI.dataGrid_DataResponse retVal = ((UI.GymAPI.WebServiceSoap)(this)).dataGrid_Data(inValue);
            return retVal.Body.dataGrid_DataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI.GymAPI.dataGrid_DataResponse> UI.GymAPI.WebServiceSoap.dataGrid_DataAsync(UI.GymAPI.dataGrid_DataRequest request) {
            return base.Channel.dataGrid_DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI.GymAPI.dataGrid_DataResponse> dataGrid_DataAsync() {
            UI.GymAPI.dataGrid_DataRequest inValue = new UI.GymAPI.dataGrid_DataRequest();
            inValue.Body = new UI.GymAPI.dataGrid_DataRequestBody();
            return ((UI.GymAPI.WebServiceSoap)(this)).dataGrid_DataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI.GymAPI.SaveResponse UI.GymAPI.WebServiceSoap.Save(UI.GymAPI.SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public void Save(string nombre, UI.GymAPI.ArrayOfFloat medidas, int edad, char genero, System.DateTime fecha) {
            UI.GymAPI.SaveRequest inValue = new UI.GymAPI.SaveRequest();
            inValue.Body = new UI.GymAPI.SaveRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.medidas = medidas;
            inValue.Body.edad = edad;
            inValue.Body.genero = genero;
            inValue.Body.fecha = fecha;
            UI.GymAPI.SaveResponse retVal = ((UI.GymAPI.WebServiceSoap)(this)).Save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI.GymAPI.SaveResponse> UI.GymAPI.WebServiceSoap.SaveAsync(UI.GymAPI.SaveRequest request) {
            return base.Channel.SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI.GymAPI.SaveResponse> SaveAsync(string nombre, UI.GymAPI.ArrayOfFloat medidas, int edad, char genero, System.DateTime fecha) {
            UI.GymAPI.SaveRequest inValue = new UI.GymAPI.SaveRequest();
            inValue.Body = new UI.GymAPI.SaveRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.medidas = medidas;
            inValue.Body.edad = edad;
            inValue.Body.genero = genero;
            inValue.Body.fecha = fecha;
            return ((UI.GymAPI.WebServiceSoap)(this)).SaveAsync(inValue);
        }
    }
}
