//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DensidadCorporal
    {
        public int Id_Paciente { get; set; }
        public string Nombre_Paciente { get; set; }
        public double Peso { get; set; }
        public double Talla { get; set; }
        public double Genero { get; set; }
        public byte Edad { get; set; }
        public double Triceps { get; set; }
        public double Biceps { get; set; }
        public double Pecho { get; set; }
        public double Axila { get; set; }
        public double Subescapular { get; set; }
        public double Suprailíaco { get; set; }
        public double Abdomen { get; set; }
        public double Muslo { get; set; }
        public double Pantorrilla { get; set; }
        public System.DateTime Fecha_Medicion { get; set; }
        public double Resultado_YUHASZ { get; set; }
        public double Resultado_JacksonPollock { get; set; }
    }
}
